### PR TITLE
Add documentation about supported NumPy functions via DPNP

### PR DESCRIPTION
**Pull request by reazulhoque**
This PR uses jinja to auto generate a stub class representing the NumPy functions we currently support. This generation also produces a generic docstring for each function that can help us in documenting which NumPy functions we support.

### CODE REVIEW

**Comment by diptorupd** [comment]
@reazulhoque what's the status on this PR? Can it be added to the docs for this release?

**Comment by reazulhoque** [comment]
No, this intriduces disruptive changes to how we implement function from dpnp in Numba_dppy and will be risky to add now.

**Review by PokhodenkoSA — COMMENTED** [review]
It is very old PR but it is actual now because @samaid asks for clear understanding what NumPy features numba-dppy support.

**Comment by diptorupd** [comment]
Too bit rotten at this point.

**Pull request closed without merging**
