### PR TITLE
Made some fixes pytests for gdb-oneapi

### PR DESCRIPTION
**Pull request by mingjie-intel**
- [x] Have you provided a meaningful PR description?
- [x] Have you added a test, reproducer or referred to an issue with a reproducer?
No new tests added, but there will be 5 failures from current tests. 
- [x] Have you tested your changes locally for CPU and GPU devices?
Expect more failures on CPU due to compiler issue. 
- [x] Have you made sure that new changes do not introduce compiler warnings?
No warning introduced.
- [x] If this PR is a work in progress, are you filing the PR as a draft?

1. Fixed test scripts to run gdb-oneapi tests.
2. Made changes to test examples to pass pytests.
3. 5 cases are failing due to numba which needs investigation.

### CODE REVIEW

**Comment by mingjie-intel** [comment]
To run gdb tests locally using conda on Gen9 to Gen12:

1. Install pytest, pytest-cov if not intalled.

2. install DCD server. run following to make sure it is activated.
`sudo modinfo igfxdcd`

3. Install or activate gdb-oneapi from oneAPI pakcage:
`source /<to_oneapi>/debugger/latest/env/var.sh`

4. Install pexpect using either way:
`conda install pexpect`
`pip install pexpect`

5. Run gdb test cases:
` python -m pytest -vvv numba_dpex/tests/debugging/`

**Comment by diptorupd** [comment]
@mingjie-intel I rebased the PR on top of main and tested locally. I think all the failures are due to TIMEOUT. I followed your steps.

> ======================= short test summary info ================================
FAILED numba_dpex/tests/debugging/test_backtraces.py::test_backtrace - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_with_condition_by_function_argument[side-by-side.py:15-numba-dpex-kernel] - pexpect.exceptions.TIM...
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_with_condition_by_function_argument[common_loop_body-numba-dpex-kernel] - pexpect.exceptions.TIMEO...
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_with_condition_by_function_argument[side-by-side.py:common_loop_body-numba-dpex-kernel] - pexpect....
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_common[simple_sum.py:data_parallel_sum-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_common[data_parallel_sum-simple_sum.py] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_common[simple_dpex_func.py:func_sum-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_breakpoints.py::test_breakpoint_with_condition_common[simple_sum.py:14 if i == 1-i-1] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[simple_sum.py:14-simple_sum.py-simple_sum.py:14-14\\s+c\\[i\\] = a\\[i\\] \\+ b\\[i\\]] - pexpect...
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[simple_sum.py:14-simple_sum.py-simple_sum.py:14-None] - pexpect.exceptions.TIMEOUT: Timeout excee...
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[simple_sum.py:14-simple_sum.py-None-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[simple_sum.py:14-None-None-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[simple_sum.py:data_parallel_sum-None-None-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_common.py::test_setup_breakpoint[data_parallel_sum-simple_sum.py-None-None] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_info.py::test_info_args[simple_dpex_func.py:19-simple_dpex_func.py-19\\s+i = dpex.get_global_id\\(0\\)-expected_args0-expected_info0]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_args[side-by-side.py:15-side-by-side.py --api=numba-dpex-kernel-None-expected_args2-expected_info2] - pexpect.e...
FAILED numba_dpex/tests/debugging/test_info.py::test_info_functions - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env0-sum_local_vars.py:16-sum_local_vars.py-16\\s+c\\[i\\] = l1 \\+ l2-expected_info_locals0-expected_info0]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env1-sum_local_vars.py:16-sum_local_vars.py-16\\s+c\\[i\\] = l1 \\+ l2-expected_info_locals1-expected_info1]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env2-side-by-side.py:18-side-by-side.py --api=numba-dpex-kernel-None-expected_info_locals2-expected_info2]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env3-side-by-side.py:18-side-by-side.py --api=numba-dpex-kernel-None-expected_info_locals3-expected_info3]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env5-side-by-side.py:17 if param_a == 5-side-by-side.py --api=numba-dpex-kernel-None-expected_info_locals5-expected_info5]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env7-side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-None-expected_info_locals7-expected_info7]
FAILED numba_dpex/tests/debugging/test_info.py::test_print_array_element[side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-expected_info1]
FAILED numba_dpex/tests/debugging/test_info.py::test_assignment_to_variable[side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-expected_info1]
FAILED numba_dpex/tests/debugging/test_side_by_side.py::test_breakpoint_row_number[numba-dpex-kernel] - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_stepping.py::test_next - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_stepping.py::test_step - pexpect.exceptions.TIMEOUT: Timeout exceeded.
FAILED numba_dpex/tests/debugging/test_stepping.py::test_stepi - pexpect.exceptions.TIMEOUT: Timeout exceeded.
=============== 29 failed, 11 passed, 9 warnings in 945.62s (0:15:45) ==================================

**Comment by mingjie-intel** [comment]
After checking the issue, it is due to test_backtrace. In the latest compiler/numba env, the backtrack is failing. Instead of printing the backtrace, now after hitting the breakpoint, the bracktrace is:

```
Thread 2.1 hit Breakpoint 1, with SIMD lanes [0-7], __main__::func_sum (a_in_func=0, b_in_func=0) at simple_dpex_func.py:13
13          result = a_in_func + b_in_func  # breakpoint location
(gdb) where
#0  __main__::func_sum (a_in_func=0, b_in_func=0) at simple_dpex_func.py:13
#1  0x0000000000000000 in ?? ()
PC not saved
```
Need to talk to Matti about this. 

Currently, the work around is to comment out the last line in /numba_dpex/tests/debugging/test_backtraces.py:
```
     app.child.expect(r"#0.*__main__::func_sum .* at simple_dpex_func.py:13")
#   app.child.expect(r"#1.*__main__::kernel_sum .* at simple_dpex_func.py:20")
```
With above fix, the gdb-oneapi works as expected: (5 errors which are related to conditional break)

```
============================================================================= short test summary info =============================================================================
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env1-sum_local_vars.py:16-sum_local_vars.py-16\\s+c\\[i\\] = l1 \\+ l2-expected_info_locals1-expected_info1] - ...
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env5-side-by-side.py:17 if param_a == 5-side-by-side.py --api=numba-dpex-kernel-None-expected_info_locals5-expected_info5]
FAILED numba_dpex/tests/debugging/test_info.py::test_info_locals[env7-side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-None-expected_info_locals7-expected_info7]
FAILED numba_dpex/tests/debugging/test_info.py::test_print_array_element[side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-expected_info1] - pexpec...
FAILED numba_dpex/tests/debugging/test_info.py::test_assignment_to_variable[side-by-side-2.py:19 if param_a == 5-side-by-side-2.py --api=numba-dpex-kernel-expected_info1] - pex...
============================================================== 5 failed, 35 passed, 9 warnings in 342.58s (0:05:42) ===============================================================
```

**Review by diptorupd — APPROVED** [review]
Thanks!

**Pull request merged**
