### PR TITLE
Add range classes to kernel_api

### PR DESCRIPTION
**Pull request by diptorupd**
- [X] Have you provided a meaningful PR description?

    Refactoring the indexer classes.
    
  - Splits up the numba_dpex.core.kernel_interface.indexers
    module and moves the Python classes into a new
    kernel_api.ranges submodule.
  - Moves the numba-dpex type definitions into
    core.types.kernel_api_types
  - Other changes as needed to get everything working
        
- [ ] Have you added a test, reproducer or referred to an issue with a reproducer?
- [X] Have you tested your changes locally for CPU and GPU devices?
- [X] Have you made sure that new changes do not introduce compiler warnings?
- [ ] If this PR is a work in progress, are you filing the PR as a draft?

### CODE REVIEW

**Review by ZzEeKkAa — APPROVED** [review]
LGTM! Just would suggest moving `numba_dpex/core/boxing.py` to `numba_dpex/core/boxing/ranges.py`

**Comment by ZzEeKkAa** [comment]
And one more, just noticed. `types/<foo>_types` to `types/<foo>` sounds better. We can always override name at import

**Comment by diptorupd** [comment]
> LGTM! Just would suggest moving `numba_dpex/core/boxing.py` to `numba_dpex/core/boxing/ranges.py`

Done in [574f799](https://github.com/IntelPython/numba-dpex/pull/1306/commits/574f799c245f1b732a51bd20934571f2e0d098f9)

**Comment by diptorupd** [comment]
> And one more, just noticed. `types/<foo>_types` to `types/<foo>` sounds better. We can always override name at import

Addressed in [9408d2c](https://github.com/IntelPython/numba-dpex/pull/1306/commits/9408d2c219c635d45cdf2a8dc176488a31fe0b6c)

**Pull request merged**
