### PR TITLE
Proposals for improving examples

### LINKED ISSUE #427: Use default device context in examples
All examples contain code for selecting device context. It is not how we recommend to code.
The better approach is to use default device context and provide possibility to select default via environment variable.

See https://github.com/IntelPython/numba-dppy/pull/426/files#r647426318.

### PR DESCRIPTION
**Pull request by PokhodenkoSA**
- Closes #428 - default device. Fixes #427.
- no `random`, use `arange`
- no `ones_like`, use `empty_like`

### CODE REVIEW

**Comment by reazulhoque** [comment]
@PokhodenkoSA I like the overall direction, can you please add the same default device selector in all examples in the same PR?

**Comment by PokhodenkoSA** [comment]
> can you please add the same default device selector in all examples in the same PR?

Yes. I will do it.

**Comment by diptorupd** [comment]
In general, using `select_default_device` is fine as far as making the examples shorter. However, I want to be careful as to advertising the use of `SYCL_DEVICE_FILTER` environment variable. Depending on how the variable is set up it may not only set up a default device, but also disable devices. E.g., `export SYCL_DEVICE_FILTER="level_zero:gpu"` will make all OpenCL device non-discoverable. For this reason, I do not want users to think that is the way we want them to control devices. 

Instead, we should show in some example that if a user wants to use something other than the default device, they should use the appropriate device selector from dpctl. Moreover, at least some examples should cover the use case where we show the same code running on multiple type of devices by changing the `device_context`.

**Comment by PokhodenkoSA** [comment]
> at least some examples should cover the use case where we show the same code running on multiple type of devices by changing the `device_context`.

I will create separate example for this.

**Review by diptorupd — APPROVED** [review]

**Comment by PokhodenkoSA** [comment]
Do not merge until I apply this changes to all examples.

**Comment by diptorupd** [comment]
The changes suggested in the PR are already implemented in the main branch,

**Pull request closed without merging**
