### PR TITLE
Remove artifacts from conda/wheel packages residing in root level

### PR DESCRIPTION
**Pull request by AndresGuzman-Ballen**
Removing files that are making their way to conda packages at root-level.

### CODE REVIEW

**Comment by ZzEeKkAa** [comment]
Thank you @AndresGuzman-Ballen ! It is actually wired it was added to wheel..

**Comment by AndresGuzman-Ballen** [comment]
No problem! Anything else you'd like me to do before merging?

**Comment by AndresGuzman-Ballen** [comment]
Friendly ping to merge this :)

**Review by oleksandr-pavlyk — APPROVED** [review]
Looks good, @AndresGuzman-Ballen . Thanks!

**Comment by AndresGuzman-Ballen** [comment]
Woohoo!

**Comment by ZzEeKkAa** [comment]
@AndresGuzman-Ballen @oleksandr-pavlyk I've just checked two builds and this PR did not affect result package.

**Comment by ZzEeKkAa** [comment]
Sorry, it did. I just extract two same packages...

**Pull request merged**
