### PR TITLE
Remove excessive pinning

### PR DESCRIPTION
**Pull request by oleksandr-pavlyk**
Modified `conda-recipe/meta.yaml` to remove excessive pinning.

- [X] Have you provided a meaningful PR description?

### CODE REVIEW

**Comment by oleksandr-pavlyk** [comment]
The reason this PR fails CI is too old a Windows build of `dpnp` on dppy channel.

It was manually built and uploaded before backwards incompatible change was pushed to dpctl that changed the size of `dpctl.SyclEvent` struct, requiring downstream projects to be rebuilt. 

Since dpnp conda package for Windows was uploaded manually that rebuilt package has not made its way to the channel yet

**Comment by oleksandr-pavlyk** [comment]
@diptorupd Once this is green, I suggest we merge it to make numba-dpex available on dppy channel.

**Comment by oleksandr-pavlyk** [comment]
This PR cherry-picked changes from #771 and hence supersedes #771.

**Comment by oleksandr-pavlyk** [comment]
@diptorupd This workflows are green, please merge this when you satisfied. Once merged #771 must be closed.

**Review by diptorupd — APPROVED** [review]
LGTM!

**Pull request merged**
